---
abstract: 'Perl pragma to declare global constants'
author:
  - 'Gary Gurevich <garygurevich at gmail>'
build_requires:
  B::Deparse: '0'
  Data::Dumper: '0'
  Test: '0'
  Test::More: '0.88'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: define
requires:
  Carp: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/define
  repository: https://github.com/neilbowers/define.git
version: '1.03'
